### ISSUE TITLE
False positives due to language_incoherence and missing language field

### ISSUE THREAD

**Issue by svynckier** [wp-blocks/cf7-antispam#44]
We're noticing quite a bit of false positive spam messages on our website due to the language functions in the plugin. I've currently disabled the language verification on the website, but would like to be able to add this extra check back in the future.

CF7 is being used for user to user messages on our website.

The most common spam log messages we find for false positive spam messages are along the lines of "language_field: missing language field" and "language_incoherence: languages detected not coherent (nl vs fr-be-en) or (nl vs fr)".

There is no language field in the contact form and adding a hard coded hidden language field wouldn't help either, as our website is being used in Belgium (and the Netherlands). Belgium is a multilingual country, so we would already exclude 3 of our national languages then. I don't know if I'm missing a specific setting here or if this is most likely a bug.

Either way, then there's also the issue with the language incoherence between the browser and the website language. We had 'en', 'nl', 'de' and 'fr' as allowed languages in the language settings, but they still seemed to get flagged anyway. Next, then there's the doubt that 'be' (see error message above) would stand for Belgium (the country, not the language, as there is no "Belgian" language. We speak nl-BE, fr-BE, de-BE and en-UK or en-US). If 'be' was the correct language code, then it would stand for Belarusian. I highly doubt that either the user has their browser in Belarusian, for this specific case, and our website doesn't have any Belarusian translations either. Our website is only available in Dutch (nl-BE) at the moment.

Lastly, this is not part of the bug, but would be great to know. Would the language settings pose a problem when a website is multilingual, seeing that there are some inconsistencies (as far as we know right now). We're looking into adding French, German and English as extra languages to our website in the near future.

**Comment by erikyo** [comment]
Thank you for bringing this to my attention, and I sincerely apologize but it's really hard to succeed at these bugs (in fact, I really appreciate you pointing it out). 

nl-BE i thought means "Duch language spoken in Belgium" (same for fr-BE etc.)

Regarding the problem you've reported, it seems that the method used to detect the language (using the browser language if geolocation is not enabled) is not functioning correctly in your case. I will thoroughly examine the language detection mechanism to identify and resolve the underlying issue. Furthermore, if it's possible, I kindly request you to send a sample spam email to our website at https://modul-r.codekraft.it/contacts/. This will greatly assist me in understanding the problem better and implementing an effective solution.

this plugin was initially created by me to "defend" an ecommerce with 5 languages, so let's say that from this point of view it is proven and you should not encounter any kind problems. 

Once again, thank you for your valuable feedback and understanding. If you have any additional information or observations, please feel free to share them.

**Comment by gardenboi** [comment]
Hi @svynckier I'm an Erik's collaborator

I am currently doing a bit of research and testing with the language field, it would be great if you could post here screenshots of your settings so I can do my verifications. 

Considering from what I have learned about the [ISO 639](https://www.fincher.org/Utilities/CountryLanguageList.shtml) and verifying the implementation in the source code you could apply the following solutions:
### _Important: Language labels must be in lowercase_

### If you use language detection only:
__Allowed browser Languages__
```
nl
de
fr
en
```

### If you use language detection **and GeoIP**:
__Allowed browser Languages__
```
nl
de
fr
en
be
```
__Disallowed browser Languages__
```
by
```

The reason for the 2nd solution lies in the souce code, that's beacuse we overlap languages with locations in the spam checks, this means you will allow Netherlands, Germany, France, England and your country to send mails without getting flagged by the b8 filter **if it's enabled**, excluding completely Belarus, alternatively you could test yourself a `third solution`, if you want to include Belgium only and exclude but I am not sure of the side effects with the current logic written in the code.

__Allowed browser Languages__
```
be
```

Since we are using GeoIP2 you can do some checks in advance if you have any doubts for adding/excluding countries [here](https://www.maxmind.com/en/geoip2-precision-demo)
IPs to test:
```
128.0.156.0
109.126.128.0
```

<br>

**_Unfortunately I am not aware of the settings used in your site so I had do hypothesize the possible scenarios, as long as you're not using GeoIP you should be totally fine with the first solution._**
